name: 'kenya_health'
version: '1.0.0'
config-version: 2

profile: 'kenya_health'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  kenya_health:
    staging:
      +materialized: view
      +schema: staging
      
    intermediate:
      +materialized: view
      +schema: intermediate
      
    marts:
      +materialized: table
      +schema: marts

seeds:
  kenya_health:
    +schema: seeds
    +column_types:
      "YEAR (DISPLAY)": varchar(50)
      "Numeric": numeric
      "Low": numeric
      "High": numeric

vars:
  current_year: 2024
  child_health_indicators:
    - "Stunting"
    - "Wasting"
    - "Underweight"
    - "Anaemia"
    - "Mortality"
